_wandb:
    value:
        cli_version: 0.23.1
        e:
            iyz5l46lbhydyyfjvi4uc6g4p74kdx5p:
                codePath: Week1\main.py
                codePathLocal: Week1\main.py
                cpu_count: 14
                cpu_count_logical: 20
                disk:
                    /:
                        total: "999250980864"
                        used: "460237672448"
                email: xavipba@gmail.com
                executable: C:\Users\xavipba\OneDrive\Escritorio\Msc Computer vision\C3 Projects\project-2\team2\Scripts\python.exe
                git:
                    commit: 4a26373197f73e02f872037d0391b396e7ef8a95
                    remote: https://github.com/MCV-C3/project-2.git
                host: XaviGaming
                memory:
                    total: "34163785728"
                os: Windows-11-10.0.22631-SP0
                program: C:\Users\xavipba\OneDrive\Escritorio\Msc Computer vision\C3 Projects\project-2\Week1\main.py
                python: CPython 3.12.0
                root: C:\Users\xavipba\OneDrive\Escritorio\Msc Computer vision\C3 Projects\project-2
                startedAt: "2025-12-03T21:38:46.137683Z"
                writerId: iyz5l46lbhydyyfjvi4uc6g4p74kdx5p
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.0
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
classifier:
    value: LogisticRegression
clf_params:
    value:
        C: 0.01
        class_weight: balanced
        max_iter: 1000
        penalty: l2
codebook_size:
    value: 50
detector:
    value: SIFT
run_id:
    value: 1
