paths:
  dataset: /kaggle/input/mit-1-small/MIT_small_train_1
  models_out_path: ./models
  plots_out_path: ./plots

data_augm: true
preset: none_frozen


optimizer:
  type: SGD
  lr: 1e-3
  weight_decay: 1e-4
  momentum: 0.4
  nesterov: false

scheduler:
  type: steplr
  step_size: 7
  gamma: 0.1

pipeline:
  batch_size: [16, 1]
  num_epochs: 20
